# Generated by Django 4.2.6 on 2023-10-29 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('str_mod', models.IntegerField(default=0, verbose_name='Модификатор силы')),
                ('agi_mod', models.IntegerField(default=0, verbose_name='Модификатор ловкости')),
                ('end_mod', models.IntegerField(default=0, verbose_name='Модификатор выносливости')),
                ('int_mod', models.IntegerField(default=0, verbose_name='Модификатор интеллекта')),
                ('wis_mod', models.IntegerField(default=0, verbose_name='Модификатор мудрости')),
                ('cha_mod', models.IntegerField(default=0, verbose_name='Модификатор обаяния')),
                ('race_health_points', models.IntegerField(default=0, verbose_name='ПЗ расы')),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('strength', models.IntegerField(default=10, verbose_name='Сила')),
                ('agility', models.IntegerField(default=10, verbose_name='Ловкость')),
                ('endurance', models.IntegerField(default=10, verbose_name='Выносливость')),
                ('intelligence', models.IntegerField(default=10, verbose_name='Интеллект')),
                ('wisdom', models.IntegerField(default=10, verbose_name='Мудрость')),
                ('charisma', models.IntegerField(default=10, verbose_name='Обаяние')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Игрок')),
                ('race', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='character', to='character.race', verbose_name='Раса')),
            ],
        ),
    ]
