# Generated by Django 4.2.6 on 2023-10-29 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='race_name',
            field=models.CharField(default=None, max_length=30, verbose_name='Раса'),
            preserve_default=False,
        ),
    ]
