# Generated by Django 4.2.6 on 2023-10-29 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0002_race_race_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_name', models.CharField(max_length=30, verbose_name='Тема')),
                ('str_mod', models.IntegerField(default=0, verbose_name='Модификатор силы')),
                ('agi_mod', models.IntegerField(default=0, verbose_name='Модификатор ловкости')),
                ('end_mod', models.IntegerField(default=0, verbose_name='Модификатор выносливости')),
                ('int_mod', models.IntegerField(default=0, verbose_name='Модификатор интеллекта')),
                ('wis_mod', models.IntegerField(default=0, verbose_name='Модификатор мудрости')),
                ('cha_mod', models.IntegerField(default=0, verbose_name='Модификатор обаяния')),
            ],
        ),
    ]
